# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 5  # Hz
    telgroup_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

telgroup_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - az_joint
      - el_joint
      - eef_joint
